modLoader="javafml"
loaderVersion="[40,41)"
license="MIT"
issueTrackerURL="https://github.com/DynamicTreesTeam/DynamicTrees-Neapolitan/issues"

[[mods]]
modId="dtneapolitan"
version="${file.jarVersion}"
displayName="Dynamic Trees for Neapolitan"

updateJSONURL="https://github.com/DynamicTreesTeam/DynamicTreesVersionInfo/blob/master/Add-ons/Neapolitan.json?raw=true"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-neapolitan"

authors="Max Hyper" #optional
description='''
Compatibility Mod between Dynamic trees and Neapolitan
'''

[[dependencies.dtneapolitan]]
    modId="forge"
    mandatory=true
    versionRange="[40,41)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtneapolitan]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtneapolitan]]
    modId="dynamictrees"
    mandatory=true
    versionRange="[1.0.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dtneapolitan]]
    modId="neapolitan"
    mandatory=true
    versionRange="[3.0.0,4.0.0)"
    ordering="AFTER"
    side="BOTH"
